# Generated by Django 5.0.8 on 2024-09-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbvapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="cbvapp.company",
            ),
        ),
    ]
