# Generated by Django 5.0.8 on 2024-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbvapp", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logo/"),
        ),
    ]
